apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: registry
  name: registry
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: registry
    spec:
      containers:
      - image: registry.cn-hangzhou.aliyuncs.com/spacexnice/registry:2.6-official
        imagePullPolicy: Always
        name: registry
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30


---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: nginx
  name: registry-svc
  namespace:
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    run: registry
  type: ClusterIP